### ISSUE TITLE
Error in if ((ninc.d > npl.incdit) | (llht < -1e+293)) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by JosetteRosine** [ahoundetoungan/CDatanet#1]
Hello,
I'm using cdnet function from CDatanet to estimate peer effects on count data. After 2 steps, I get this error message:
Error in if ((ninc.d > npl.incdit) | (llht < -1e+293)) { : missing value where TRUE/FALSE needed
Can you help me to fit this error?

**Comment by ahoundetoungan** [comment]
Hi,
Thanks for raising this issue.
This problem is caused by the solver failing to find a solution at one iteration. Sometimes, changing your starting point or reduce the value of the setting R may fix the issue. 
Can you give more details about the distribution of the dependent variable (min, max, Q1, Q3)? What value of R did you choose? Can you also post the code you ran to get this error?
Thanks

**Comment by JosetteRosine** [comment]
Hi,
Thanks for your response,
Here is the distribution of my dependent variable (min=0.000; Q1=0.000; Median=0.000; Mean=1.023; Q3=2.000 and max=9).
I ran this code:

library(CDatanet)
summary(mydata$nt1)
mod1 <- cdnet(formula = nt1 ~ age1+grade1+female+socialaccep1+
               momrelsatisf1+fatrelsatisf1+psycouns1+parentargbehave1+phyagress1+
               hispanic+white+black+american+asian+fincome1, contextual = FALSE, Glist = G1,
             data = mydata,  estim.rho = TRUE)

The majority of explanatory variables are binary (socialaccep1, momrelsatisf1, fatrelsatisf1, psycouns1, parentargbehave1, phyagress1, hispanic, white, black, American, asian)

**Comment by ahoundetoungan** [comment]
Two solutions:
1. Start the estimation with Rbar = 1, and you will increase Rbar gradually and use the previous estimates as starting point for the next one. 
2. You could also change the solver, optimizer = "optim" or optimizer = "nlm".

**Comment by JosetteRosine** [comment]
Do you mean by the first solution that: I will set Rbar=1 and run? If no convergence, I will use the parameter values from step 1 as starting values and now set Rbar=2, and so on.

**Comment by ahoundetoungan** [comment]
Rbar is a parameter the user needs to choose. Because you don't set Rbar, the program sets a default value that may not be convenient.

**Comment by ahoundetoungan** [comment]
I got another question about the same issue and have now taken a look at it more seriously. The issue comes from the numerical optimization with c++. I submitted a new version of the package to CRAN which solves the issue. Could you check and let me know if everything is fine?

Make sure to install the latest version of the package. You might do `install.packages(CDatanet, repos = NULL, type="source")` to install from source because the binary for windows is not ready yet. Another way is to install the latest version from GitHub by doing `remotes::install_github("ahoundetoungan/CDatanet")`.

If you still get an error, you can change the optimizer. In the function `cdnet` you can change the optimizer with the argument `optimizer`, for example by using `optim` or `nlm` instead of `fastlbfgs` (which is the the default value). Please check the function help with `?cdnet`.
